# Generated by Django 3.1.6 on 2021-03-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('userid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'account_test',
            },
        ),
    ]
