CREATE INDEX I_MOVIE_RELEASE ON MOVIE (MOVIE_RELEASE ASC);

CREATE INDEX I_SHOW_START ON SHOW (SHOW_START_TIME ASC);
CREATE INDEX I_SHOW_MOVIE ON SHOW (MOVIE_ID ASC);

CREATE INDEX I_TICKET_PAY ON TICKET (PAY_ID ASC);
CREATE INDEX I_TICKET_SEAT ON TICKET (SEAT_ID ASC);
CREATE INDEX I_TICKET_USR ON TICKET (USR_ID ASC);
CREATE INDEX I_TICKET_SHOW ON TICKET (SHOW_ID ASC);

CREATE INDEX I_USR_EMAIL ON USR (USR_EMAIL ASC);
