CREATE SEQUENCE MOVIE_SEQ
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE SEQUENCE PAY_SEQ
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE SEQUENCE SEAT_SEQ
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE SEQUENCE SHOW_SEQ
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE SEQUENCE THEATER_SEQ
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE SEQUENCE TICKET_SEQ
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
