CREATE SEQUENCE MOVIE_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE PAY_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE SEAT_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE SHOW_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE THEATER_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE TICKET_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE USR_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE; -- 비회원용
