CREATE SEQUENCE MOVIE_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE PAY_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE SEAT_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE SHOW_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE THEATER_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE TICKET_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE USR_SEQ
  START WITH 1
  INCREMENT BY 1; -- 비회원용
